# Generated by Django 3.2.18 on 2023-03-17 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModelImage',
            fields=[
                ('baseimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilities.baseimage')),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('caption', models.CharField(blank=True, default='', max_length=191)),
                ('test_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.testmodel')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
            bases=('utilities.baseimage',),
        ),
    ]
